// components/Static/Footer.tsx
const Footer = () => {
  return (
    <footer className="text-white text-center mt-32 mb-4 sm:text-lg md:text-xl">
      <p>
        Made with ❤️ by{' '}
        <a className="text-blue-500" href="https://github.com/TheRealToxicDev">
          Toxic Dev
        </a>
      </p>
      <p>© 2022, Infinity Development</p>
    </footer>
  )
}

export default Footer

// layouts/Footer.vue
<template>
	<footer class="text-white text-center mt-32 mb-4 sm:text-lg md:text-xl">
		<p>Made with ❤️ by <a class="text-blue-500" href="https://github.com/TheRealToxicDev">Toxic Dev</a></p>
		<p>© 2022, Infinity Development</p>
	</footer>
</template>

<script>
export default {
	name: 'Footer',
}
</script>
